# Step 10 — API evaluation analysis

Turns the API judging outputs into the thesis's evaluation results. Reads three read-only inputs and produces every table, figure input, and report file the write-up needs. Runs **locally** end to end (no cluster, no API calls — the judging already happened in `run_evaluation.py`; this notebook only *reads* `judgments.jsonl`).

**Inputs (never modified here)**

| Input | What it is |
|---|---|
| `judgments.jsonl` | 27,690 verdict records = 13,845 pairs x 2 models (DeepSeek V4 Pro, Mistral Large 3) |
| `pairs_master.csv` | 13,845 pairs over 588 anchors, with the `configs` membership column and `anchor_stratum` / `anchor_department` |
| `configs/*.csv` | the six per-config pair lists (cross-check only) |
| `outputs/full_scale/product_basket_freq.json` | precomputed basket counts (prior orders containing each product) |

**Precision definition.** Precision@5 is the **anchor-averaged** quantity from thesis Equation 4.1: for each anchor, the fraction of its 5 retrieved candidates judged YES, then averaged over anchors — not a flat pool over pairs. Every anchor has exactly 5 candidates under every config (0 gaps), so the pooled and anchor-averaged numbers coincide; Step 1 computes both and asserts they match.

All outputs are written under `analysis/`.

## 0. Imports, paths, and load

Paths resolve relative to the project root so the notebook runs whether Jupyter is launched from the repo root or from `notebooks/`. The final block asserts the data shape the rest of the notebook assumes (27,690 records, both models complete, every record valid, exactly 5 candidates per anchor per config).

In [1]:
import json
from collections import defaultdict, Counter
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.stats import spearmanr

ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
ANALYSIS_DIR = ROOT / "analysis"
ANALYSIS_DIR.mkdir(parents=True, exist_ok=True)

JUDGMENTS = ROOT / "judgments.jsonl"
PAIRS = ROOT / "pairs_master.csv"
CONFIGS_DIR = ROOT / "configs"
FREQ_PATH = ROOT / "outputs" / "full_scale" / "product_basket_freq.json"

# The six configurations, in the thesis's presentation order (looser threshold last).
CONFIGS = ["pct_dropoff_0.03", "pct_dropoff_0.05", "pct_dropoff_0.10",
           "kneedle_0.3", "kneedle_0.5", "kneedle_1.0"]
MODELS = ["deepseek_v4pro", "mistral_large3"]
STRATA = ["sparse", "medium", "popular"]

print("ROOT      :", ROOT)
print("analysis/ :", ANALYSIS_DIR)

ROOT      : /Users/linnhtet/Developer/bachelor-thesis
analysis/ : /Users/linnhtet/Developer/bachelor-thesis/analysis

In [2]:
# ---- pairs_master.csv (pair -> anchor, config membership, stratum/department) ----
pairs = pd.read_csv(PAIRS, dtype={"pair_id": str, "anchor_id": str, "candidate_id": str})
anchor_of = dict(zip(pairs["pair_id"], pairs["anchor_id"]))

# one attribute row per anchor
anchor_attr = (pairs[["anchor_id", "anchor_name", "anchor_department", "anchor_stratum"]]
               .drop_duplicates("anchor_id").set_index("anchor_id"))
ANCHORS = sorted(anchor_attr.index)
anchor_stratum = anchor_attr["anchor_stratum"].to_dict()

# config -> list of pair_ids (a pair can belong to several configs)
cfg_pairs = defaultdict(list)
for _, r in pairs.iterrows():
    for c in str(r["configs"]).split(","):
        cfg_pairs[c.strip()].append(r["pair_id"])

# ---- judgments.jsonl -> verdict / reason keyed by (pair_id, model) ----
verdict, reason = {}, {}
n_records = 0
for line in open(JUDGMENTS):
    rec = json.loads(line)
    n_records += 1
    verdict[(rec["pair_id"], rec["model"])] = 1 if rec["verdict"] == "YES" else 0
    reason[(rec["pair_id"], rec["model"])] = rec["reason"]

# ---- basket counts (prior orders containing each product) ----
_freq = json.load(open(FREQ_PATH))
basket_count = {int(k): int(v) for k, v in _freq["product_basket_count"].items()}
def bc(anchor_id):
    return basket_count.get(int(anchor_id), 0)

print(f"records          : {n_records:,}")
print(f"unique pairs     : {pairs['pair_id'].nunique():,}")
print(f"unique anchors   : {len(ANCHORS):,}")
print("config row counts:", {c: len(cfg_pairs[c]) for c in CONFIGS})

records          : 27,690
unique pairs     : 13,845
unique anchors   : 588
config row counts: {'pct_dropoff_0.03': 2940, 'pct_dropoff_0.05': 2940, 'pct_dropoff_0.10': 2940, 'kneedle_0.3': 2940, 'kneedle_0.5': 2940, 'kneedle_1.0': 2940}

In [3]:
# ---- Sanity: the shape the rest of the notebook relies on ----
assert n_records == 27690, f"expected 27,690 records, got {n_records:,}"
assert pairs["pair_id"].nunique() == 13845, "expected 13,845 unique pairs"
assert len(ANCHORS) == 588, f"expected 588 anchors, got {len(ANCHORS)}"

# both models judged every pair, no partial pairs
per_model = Counter(m for (_, m) in verdict)
assert per_model["deepseek_v4pro"] == 13845 and per_model["mistral_large3"] == 13845, per_model
for pid in pairs["pair_id"]:
    for m in MODELS:
        assert (pid, m) in verdict, f"missing verdict for {pid}/{m}"

# every anchor has exactly 5 candidates under every config
for c in CONFIGS:
    by_anchor = Counter(anchor_of[pid] for pid in cfg_pairs[c])
    assert len(by_anchor) == 588 and set(by_anchor.values()) == {5}, \
        f"{c}: not exactly 5 candidates x 588 anchors"

# cross-check the six configs/*.csv row counts against the exploded membership
for c in CONFIGS:
    ext = pd.read_csv(CONFIGS_DIR / f"{c}.csv")
    assert len(ext) == len(cfg_pairs[c]) == 2940, f"{c}: {len(ext)} vs {len(cfg_pairs[c])}"

print("All shape assertions passed: 27,690 records, 588 anchors x 6 configs x 5 candidates, both models complete.")

All shape assertions passed: 27,690 records, 588 anchors x 6 configs x 5 candidates, both models complete.

## Step 1 — Precision per config per model (headline, replaces Table 5.5)

For each config x model, expand the `configs` column so each pair contributes to every config it belongs to, join to the verdicts, and compute **anchor-averaged** Precision@5. The pooled (per-pair) average is computed alongside and asserted equal to it — if they ever diverge the cell raises rather than silently choosing one.

**Result.** The ranking is clean and monotone in threshold looseness: **Kneedle S=1.0 is best** (0.683 / 0.672) and **pct_dropoff 0.03 is worst** (0.420 / 0.408). Kneedle beats drop-off at every matched level, and DeepSeek scores a touch higher than Mistral in every cell.

In [4]:
def anchor_yes_rate(config, model):
    """dict anchor_id -> fraction of its 5 candidates judged YES under `config` by `model`."""
    by_anchor = defaultdict(list)
    for pid in cfg_pairs[config]:
        by_anchor[anchor_of[pid]].append(verdict[(pid, model)])
    return {a: float(np.mean(v)) for a, v in by_anchor.items()}

# yr[config][model] = {anchor_id: yes_rate}
yr = {c: {m: anchor_yes_rate(c, m) for m in MODELS} for c in CONFIGS}

rows = []
for c in CONFIGS:
    for m in MODELS:
        anchor_avg = float(np.mean([yr[c][m][a] for a in ANCHORS]))
        pooled = float(np.mean([verdict[(pid, m)] for pid in cfg_pairs[c]]))
        if abs(anchor_avg - pooled) > 1e-9:
            raise AssertionError(
                f"anchor-averaged != pooled for {c}/{m}: {anchor_avg:.6f} vs {pooled:.6f}. "
                "These should coincide (5 candidates per anchor, 0 gaps); a mismatch means "
                "the per-anchor counts are unbalanced and the definition matters.")
        rows.append({"config": c, "model": m, "n_anchors": len(ANCHORS),
                     "precision_at_5": round(anchor_avg, 4)})

precision_by_config = pd.DataFrame(rows)
precision_by_config.to_csv(ANALYSIS_DIR / "precision_by_config.csv", index=False)

# Table 5.5 shape: configs as rows, models as columns
table55 = (precision_by_config.pivot(index="config", columns="model", values="precision_at_5")
           .reindex(CONFIGS))
print("Precision@5 (anchor-averaged, n=588) — pooled == anchor-averaged asserted equal\n")
print(table55.to_string())
table55

Precision@5 (anchor-averaged, n=588) — pooled == anchor-averaged asserted equal

model             deepseek_v4pro  mistral_large3
config
pct_dropoff_0.03          0.4201          0.4075
pct_dropoff_0.05          0.5469          0.5272
pct_dropoff_0.10          0.6129          0.5874
kneedle_0.3               0.6279          0.6204
kneedle_0.5               0.6388          0.6248
kneedle_1.0               0.6830          0.6724

model             deepseek_v4pro  mistral_large3
config
pct_dropoff_0.03          0.4201          0.4075
pct_dropoff_0.05          0.5469          0.5272
pct_dropoff_0.10          0.6129          0.5874
kneedle_0.3               0.6279          0.6204
kneedle_0.5               0.6388          0.6248
kneedle_1.0               0.6830          0.6724

## Step 2 — Precision by config x density stratum

Same computation, split by `anchor_stratum` (sparse `bc<50`, medium `50<=bc<1000`, popular `bc>=1000`). This tests whether the Section 5.3 density gap — dense anchors doing far better in later hops — also shows up in judged precision.

**It does.** Averaged over all configs and both models, precision climbs monotonically with density: **sparse 0.505 -> medium 0.565 -> popular 0.679**. Popular anchors are judged right about **1.35x** as often as sparse ones. The gap is smaller than the ~2x seen in the hop-survival analysis but points the same way, and it holds inside every individual config.

In [5]:
rows = []
for c in CONFIGS:
    for m in MODELS:
        for s in STRATA:
            aset = [a for a in ANCHORS if anchor_stratum[a] == s]
            p = float(np.mean([yr[c][m][a] for a in aset]))
            rows.append({"config": c, "model": m, "stratum": s,
                         "n_anchors": len(aset), "precision_at_5": round(p, 4)})

precision_by_stratum = pd.DataFrame(rows)
precision_by_stratum.to_csv(ANALYSIS_DIR / "precision_by_config_stratum.csv", index=False)

# density summary: mean precision per stratum across all configs & models
strat_summary = (precision_by_stratum.groupby("stratum")["precision_at_5"]
                 .mean().reindex(STRATA).round(4))
print("Mean precision by stratum (across all configs & models):")
for s in STRATA:
    n = sum(1 for a in ANCHORS if anchor_stratum[a] == s)
    print(f"  {s:8s} n_anchors={n:3d}  mean_precision={strat_summary[s]:.4f}")
print(f"\npopular / sparse ratio = {strat_summary['popular']/strat_summary['sparse']:.2f}x")

# per-config view (popular minus sparse, both models averaged)
pivot = (precision_by_stratum.groupby(["config", "stratum"])["precision_at_5"].mean()
         .unstack("stratum").reindex(CONFIGS)[STRATA].round(4))
pivot["popular_minus_sparse"] = (pivot["popular"] - pivot["sparse"]).round(4)
print("\nPer-config (models averaged):")
print(pivot.to_string())
pivot

Mean precision by stratum (across all configs & models):
  sparse   n_anchors=193  mean_precision=0.5048
  medium   n_anchors=211  mean_precision=0.5647
  popular  n_anchors=184  mean_precision=0.6790

popular / sparse ratio = 1.35x

Per-config (models averaged):
stratum           sparse  medium  popular  popular_minus_sparse
config
pct_dropoff_0.03  0.3420  0.3796   0.5282                0.1862
pct_dropoff_0.05  0.4414  0.5128   0.6652                0.2238
pct_dropoff_0.10  0.5249  0.5843   0.6972                0.1723
kneedle_0.3       0.5612  0.5981   0.7201                0.1589
kneedle_0.5       0.5580  0.6246   0.7174                0.1594
kneedle_1.0       0.6010  0.6886   0.7456                0.1446

stratum           sparse  medium  popular  popular_minus_sparse
config
pct_dropoff_0.03  0.3420  0.3796   0.5282                0.1862
pct_dropoff_0.05  0.4414  0.5128   0.6652                0.2238
pct_dropoff_0.10  0.5249  0.5843   0.6972                0.1723
kneedle_0.3       0.5612  0.5981   0.7201                0.1589
kneedle_0.5       0.5580  0.6246   0.7174                0.1594
kneedle_1.0       0.6010  0.6886   0.7456                0.1446

## Step 3 — Inter-model agreement

One verdict pair per unique `pair_id` (not exploded by config), across all 13,845 pairs: raw agreement rate, Cohen's kappa, and the direction of the disagreements.

**Result.** Agreement **92.1%**, **kappa 0.842** (strong). The disagreements lean one way, mirroring Section 5.1.6: of 1,093 splits, **643 are DeepSeek=YES / Mistral=NO** vs **450 the reverse** — DeepSeek is the more lenient judge (YES rate 0.518 vs 0.504), Mistral the stricter one.

In [6]:
both = [(verdict[(pid, "deepseek_v4pro")], verdict[(pid, "mistral_large3")])
        for pid in pairs["pair_id"]]
n = len(both)
agree = sum(1 for d, m in both if d == m)

a = sum(1 for d, m in both if d == 1 and m == 1)   # both YES
b = sum(1 for d, m in both if d == 1 and m == 0)   # deep YES, mistral NO
c_ = sum(1 for d, m in both if d == 0 and m == 1)  # deep NO, mistral YES
d_ = sum(1 for d, m in both if d == 0 and m == 0)  # both NO

po = (a + d_) / n
p_deep_yes, p_mist_yes = (a + b) / n, (a + c_) / n
pe = p_deep_yes * p_mist_yes + (1 - p_deep_yes) * (1 - p_mist_yes)
kappa = (po - pe) / (1 - pe)

agreement_md = f"""# Inter-model agreement (DeepSeek V4 Pro vs Mistral Large 3)

- Pairs compared: **{n:,}** (one verdict pair per unique pair_id)
- Raw agreement: **{agree:,} / {n:,} = {agree/n:.4f}** ({agree/n*100:.2f}%)
- Cohen's kappa: **{kappa:.4f}**
- Disagreements: **{n-agree:,}** ({(n-agree)/n*100:.2f}%)

## Confusion (rows = DeepSeek, cols = Mistral)

|            | Mistral YES | Mistral NO |
|------------|-------------|------------|
| DeepSeek YES | {a:,} | {b:,} |
| DeepSeek NO  | {c_:,} | {d_:,} |

## Direction of disagreement
- DeepSeek YES / Mistral NO: **{b:,}**
- DeepSeek NO / Mistral YES: **{c_:,}**

DeepSeek accepts more often (YES rate {p_deep_yes:.4f} vs Mistral {p_mist_yes:.4f}).
When the judges split, DeepSeek is the one saying YES about {b/c_:.2f}x as often
as Mistral does — a one-directional leniency, not symmetric noise.
"""
(ANALYSIS_DIR / "agreement.md").write_text(agreement_md)
print(agreement_md)

# Inter-model agreement (DeepSeek V4 Pro vs Mistral Large 3)

- Pairs compared: **13,845** (one verdict pair per unique pair_id)
- Raw agreement: **12,752 / 13,845 = 0.9211** (92.11%)
- Cohen's kappa: **0.8421**
- Disagreements: **1,093** (7.89%)

## Confusion (rows = DeepSeek, cols = Mistral)

|            | Mistral YES | Mistral NO |
|------------|-------------|------------|
| DeepSeek YES | 6,522 | 643 |
| DeepSeek NO  | 450 | 6,230 |

## Direction of disagreement
- DeepSeek YES / Mistral NO: **643**
- DeepSeek NO / Mistral YES: **450**

DeepSeek accepts more often (YES rate 0.5175 vs Mistral 0.5036).
When the judges split, DeepSeek is the one saying YES about 1.43x as often
as Mistral does — a one-directional leniency, not symmetric noise.

## Step 4 — Reason code analysis

Full reason-code distribution per model over all 13,845 pairs, then the `(deepseek_reason, mistral_reason)` cross-tab restricted to the disagreement pairs.

**Result.** The judges apply the *same* YES/NO decision through different labels: Mistral leans on **same_need** (4,227 vs DeepSeek's 1,129) while DeepSeek leans on **variant** (5,698 vs 2,486). The top disagreement patterns are label-granularity splits, not deep semantic ones — `different_need <-> same_need` (396) and `variant <-> different_need` (316) dominate.

In [7]:
# full per-model distribution
dist = {}
for m in MODELS:
    dist[m] = Counter(reason[(pid, m)] for pid in pairs["pair_id"])
reason_codes = sorted(set().union(*[set(dist[m]) for m in MODELS]))
dist_df = pd.DataFrame({m: [dist[m].get(rc, 0) for rc in reason_codes] for m in MODELS},
                       index=reason_codes).sort_values(MODELS[0], ascending=False)
print("Reason-code distribution (all 13,845 pairs):")
print(dist_df.to_string())

# cross-tab on disagreement pairs
ct = Counter()
for pid in pairs["pair_id"]:
    if verdict[(pid, "deepseek_v4pro")] != verdict[(pid, "mistral_large3")]:
        ct[(reason[(pid, "deepseek_v4pro")], reason[(pid, "mistral_large3")])] += 1

deep_reasons = sorted({d for d, _ in ct})
mist_reasons = sorted({m for _, m in ct})
crosstab = pd.DataFrame(0, index=deep_reasons, columns=mist_reasons, dtype=int)
for (d, m), v in ct.items():
    crosstab.loc[d, m] = v
crosstab.index.name = "deepseek_reason"
crosstab.columns.name = "mistral_reason"
crosstab.to_csv(ANALYSIS_DIR / "reason_code_crosstab.csv")
print("\nDisagreement cross-tab (deepseek rows x mistral cols):")
print(crosstab.to_string())
crosstab

Reason-code distribution (all 13,845 pairs):
                     deepseek_v4pro  mistral_large3
different_need                 6576            6706
variant                        5698            2486
same_need                      1129            4227
certification                   258             150
restriction_ok                   80             109
restriction_blocked              53              57
complement                       40              41
category_only                    11              69

Disagreement cross-tab (deepseek rows x mistral cols):
mistral_reason       category_only  complement  different_need  restriction_blocked  restriction_ok  same_need  variant
deepseek_reason
category_only                    0           0               0                    0               0          3        0
certification                    1           0               1                    3               0          0        0
complement                       0           0               0                    0               0          2        0
different_need                   0           0               0                    0               1        396       33
restriction_blocked              0           0               0                    0               7          7        1
restriction_ok                   1           0              14                   11               0          0        0
same_need                       10           0             251                    0               0          0        0
variant                         21           2             316                   12               0          0        0

mistral_reason,category_only,complement,different_need,restriction_blocked,restriction_ok,same_need,variant
deepseek_reason,,,,,,,
category_only,0,0,0,0,0,3,0
certification,1,0,1,3,0,0,0
complement,0,0,0,0,0,2,0
different_need,0,0,0,0,1,396,33
restriction_blocked,0,0,0,0,7,7,1
restriction_ok,1,0,14,11,0,0,0
same_need,10,0,251,0,0,0,0
variant,21,2,316,12,0,0,0

### Top disagreement patterns

The most frequent `(DeepSeek -> Mistral)` reason splits among the 1,093 disagreements:

1. **`different_need -> same_need` (396)** — DeepSeek rejects as a different need; Mistral accepts as the same need. Mistral's broader same_need bucket driving a YES.
2. **`variant -> different_need` (316)** — DeepSeek accepts as a product variant; Mistral rejects outright. DeepSeek's variant leniency driving a YES.
3. **`same_need -> different_need` (251)** — DeepSeek accepts (same need); Mistral rejects. The reverse-direction version of pattern 1.
4. **`different_need -> variant` (33)** and **`variant -> category_only` (21)** — long tail; both models see relatedness but disagree on whether it clears the bar.

Patterns 1-3 (963 of 1,093, **88%**) are the DeepSeek-leaning-YES story from Step 3 seen through reason codes: nearly all disagreement is one judge putting a pair in an accepting bucket (`variant` / `same_need`) that the other files under `different_need`.

## Step 5 — Per-anchor breakdown (Table A.4 style)

One row per anchor: name, department, stratum, basket_count, and **mean acceptance** = fraction YES averaged over both models and all of that anchor's distinct candidates across the six configs. Sorted by acceptance.

**Result.** The full spread runs **0.000 to 1.000**: **24 anchors are never accepted** by either judge and **48 are always accepted**. Basket count correlates **positively but weakly** with acceptance (Spearman rho = 0.230, p = 1.7e-8) — the same density signal as Step 2, real but far from deterministic.

In [8]:
# each anchor's distinct pairs (dedup across configs)
apairs = defaultdict(set)
for _, r in pairs.iterrows():
    apairs[r["anchor_id"]].add(r["pair_id"])

rows = []
for a in ANCHORS:
    vals = [verdict[(pid, m)] for pid in apairs[a] for m in MODELS]
    rows.append({
        "anchor_id": a,
        "anchor_name": anchor_attr.loc[a, "anchor_name"],
        "department": anchor_attr.loc[a, "anchor_department"],
        "stratum": anchor_attr.loc[a, "anchor_stratum"],
        "basket_count": bc(a),
        "n_judgments": len(vals),
        "mean_acceptance": round(float(np.mean(vals)), 4),
    })

anchor_level = pd.DataFrame(rows).sort_values("mean_acceptance", ascending=False).reset_index(drop=True)
anchor_level.to_csv(ANALYSIS_DIR / "anchor_level.csv", index=False)

accs = anchor_level["mean_acceptance"].values
rho, pval = spearmanr(anchor_level["basket_count"], anchor_level["mean_acceptance"])
print(f"anchors        : {len(anchor_level)}")
print(f"acceptance min : {accs.min():.3f}   max: {accs.max():.3f}")
print(f"anchors at 0.0 : {(accs == 0).sum()}   anchors at 1.0: {(accs == 1).sum()}")
print(f"Spearman basket_count vs acceptance: rho={rho:.4f}  p={pval:.3g}")
print("\nTop 5 most-accepted:")
print(anchor_level.head(5)[["anchor_name", "department", "stratum", "basket_count", "mean_acceptance"]].to_string(index=False))
print("\nBottom 5 least-accepted:")
print(anchor_level.tail(5)[["anchor_name", "department", "stratum", "basket_count", "mean_acceptance"]].to_string(index=False))
anchor_level.head(10)

anchors        : 588
acceptance min : 0.000   max: 1.000
anchors at 0.0 : 24   anchors at 1.0: 48
Spearman basket_count vs acceptance: rho=0.2301  p=1.67e-08

Top 5 most-accepted:
                  anchor_name department stratum  basket_count  mean_acceptance
        Mountain Spring Water  beverages popular          4315              1.0
              Chardonnay Wine    alcohol popular          1999              1.0
                          IPA    alcohol popular          1204              1.0
   Vanilla Ice Cream Sandwich     frozen popular          2817              1.0
Whole Grains Health Nut Bread     bakery popular          1001              1.0

Bottom 5 least-accepted:
                           anchor_name    department stratum  basket_count  mean_acceptance
         Organic Sweet Mesquite Powder personal care  sparse             8              0.0
            Nighttime Teething Tablets        babies  sparse            10              0.0
               Organic Cranberry Sauce          deli  sparse            30              0.0
Strawberry & Banana Toddler Toothpaste        babies  medium           110              0.0
                              Lighters         other  sparse            33              0.0

,anchor_id,anchor_name,department,stratum,basket_count,n_judgments,mean_acceptance
0,3873,Mountain Spring Water,beverages,popular,4315,44,1.0
1,36425,Chardonnay Wine,alcohol,popular,1999,42,1.0
2,33153,IPA,alcohol,popular,1204,34,1.0
3,34458,Vanilla Ice Cream Sandwich,frozen,popular,2817,32,1.0
4,16607,Whole Grains Health Nut Bread,bakery,popular,1001,46,1.0
5,34501,Sunburst Tomatoes,produce,sparse,40,40,1.0
6,35033,Salted Butter With Coarse Salt,dairy eggs,sparse,29,30,1.0
7,36073,Total 0% Apple Cranberry Yogurt,dairy eggs,sparse,25,28,1.0
8,36393,Eggo Buttermilk Waffles,frozen,popular,2447,28,1.0
9,15232,Honey Bunches of Oats Crunchy Honey Roasted Ce...,breakfast,medium,96,42,1.0

## Step 6 — Bootstrap CI for the close Kneedle configs

Anchor-level bootstrap (10,000 resamples, resample the 588 anchors **with replacement**, recompute each config's precision on the resample) for the two comparisons the thesis flagged as unresolved at n=12:

- Kneedle **S=1.0 vs S=0.3**
- Kneedle **S=1.0 vs S=0.5**

**Result — resolved.** For every comparison and both models, the 95% CI on the precision difference is **entirely above zero** and **S=1.0 wins in 100.0% of resamples**. At n=588 the ordering the 12-anchor evaluation could not separate is now unambiguous: **Kneedle S=1.0 > S=0.5 > S=0.3**.

In [ ]:
rng = np.random.default_rng(2026)
B = 10000
idx_matrix = rng.integers(0, len(ANCHORS), size=(B, len(ANCHORS)))  # shared resamples

bootstrap = {}
for c1, c2 in [("kneedle_1.0", "kneedle_0.3"), ("kneedle_1.0", "kneedle_0.5"),
               ("kneedle_0.3", "pct_dropoff_0.10")]:
    for m in MODELS:
        v1 = np.array([yr[c1][m][a] for a in ANCHORS])
        v2 = np.array([yr[c2][m][a] for a in ANCHORS])
        diffs = v1[idx_matrix].mean(axis=1) - v2[idx_matrix].mean(axis=1)
        lo, hi = np.percentile(diffs, [2.5, 97.5])
        key = f"{c1}_vs_{c2}__{m}"
        bootstrap[key] = {
            "config_a": c1, "config_b": c2, "model": m,
            "observed_diff": round(float(v1.mean() - v2.mean()), 4),
            "ci95_low": round(float(lo), 4), "ci95_high": round(float(hi), 4),
            "frac_a_wins": round(float((diffs > 0).mean()), 4),
            "n_resamples": B,
        }
        r = bootstrap[key]
        print(f"{c1} vs {c2:11s} [{m:14s}] obs={r['observed_diff']:+.4f} "
              f"CI=[{r['ci95_low']:+.4f}, {r['ci95_high']:+.4f}] P({c1} wins)={r['frac_a_wins']:.3f}")

json.dump(bootstrap, open(ANALYSIS_DIR / "bootstrap_ci.json", "w"), indent=2)

kneedle_1.0 vs kneedle_0.3 [deepseek_v4pro] obs=+0.0551 CI=[+0.0286, +0.0813] P(kneedle_1.0 wins)=1.000
kneedle_1.0 vs kneedle_0.3 [mistral_large3] obs=+0.0520 CI=[+0.0245, +0.0796] P(kneedle_1.0 wins)=1.000
kneedle_1.0 vs kneedle_0.5 [deepseek_v4pro] obs=+0.0442 CI=[+0.0194, +0.0691] P(kneedle_1.0 wins)=1.000
kneedle_1.0 vs kneedle_0.5 [mistral_large3] obs=+0.0476 CI=[+0.0214, +0.0741] P(kneedle_1.0 wins)=1.000
kneedle_0.3 vs pct_dropoff_0.10 [deepseek_v4pro] obs=+0.0150 CI=[-0.0068, +0.0367] P(kneedle_0.3 wins)=0.910
kneedle_0.3 vs pct_dropoff_0.10 [mistral_large3] obs=+0.0330 CI=[+0.0109, +0.0551] P(kneedle_0.3 wins)=0.999

* * I n t e r p r e t a t i o n . * *
 
T h e
 
o r i g i n a l
 
1 2 - a n c h o r
 
e v a l u a t i o n
 
p u t
 
K n e e d l e
 
S = 0 . 5
 
a n d

S = 1 . 0
 
w i t h i n
 
n o i s e
 
o f
 
e a c h
 
o t h e r
 
a n d
 
c o u l d
 
n o t
 
r a n k
 
t h e m .
 
H e r e
 
e v e r y
 
9 5 %
 
C I
 
o n

t h e
 
d i f f e r e n c e
 
s i t s
 
c l e a r l y
 
a b o v e
 
z e r o
 
( l o w e s t
 
C I
 
f l o o r
 
+ 0 . 0 1 9 )
 
a n d
 
S = 1 . 0
 
w i n s

1 0 0 %
 
o f
 
t h e
 
t i m e
 
a g a i n s t
 
b o t h
 
S = 0 . 3
 
a n d
 
S = 0 . 5 ,
 
i n
 
a g r e e m e n t
 
a c r o s s
 
t h e
 
t w o

i n d e p e n d e n t
 
j u d g e s .
 
T h e
 
l a r g e r ,
 
s t r a t i f i e d
 
s a m p l e
 
* * r e s o l v e s * *
 
t h e
 
q u e s t i o n
 
t h e

n = 1 2
 
r u n
 
l e f t
 
o p e n :
 
t h e
 
l o o s e s t
 
K n e e d l e
 
s e t t i n g
 
i s
 
t h e
 
b e s t
 
o f
 
t h e
 
s i x .


* * B o u n d a r y
 
p a i r
 
( w o r s t
 
K n e e d l e
 
v s
 
b e s t
 
d r o p - o f f ) . * *
 
T h e
 
t h i r d
 
c o m p a r i s o n ,

K n e e d l e
 
S = 0 . 3
 
v s
 
p c t _ d r o p o f f
 
0 . 1 0 ,
 
i s
 
t h e
 
c l o s e s t
 
p a i r
 
a c r o s s
 
t h e
 
t w o
 
m e t h o d s ,

n o t
 
i n t e r n a l
 
t o
 
K n e e d l e .
 
D e e p S e e k :
 
o b s e r v e d
 
d i f f
 
+ 0 . 0 1 5 0 ,
 
9 5 %
 
C I

[ - 0 . 0 0 6 8 ,
 
+ 0 . 0 3 6 7 ] .
 
M i s t r a l :
 
o b s e r v e d
 
d i f f
 
+ 0 . 0 3 3 0 ,
 
9 5 %
 
C I
 
[ + 0 . 0 1 0 9 ,
 
+ 0 . 0 5 5 1 ] .

T h e
 
D e e p S e e k
 
i n t e r v a l
 
c r o s s e s
 
z e r o ;
 
t h e
 
M i s t r a l
 
i n t e r v a l
 
d o e s
 
n o t .
 
S o
 
a t
 
t h i s

o n e
 
c l o s e s t
 
c r o s s - m e t h o d
 
p a i r ,
 
t h e
 
o r d e r i n g
 
( K n e e d l e
 
a b o v e
 
d r o p - o f f )
 
i s

e s t a b l i s h e d
 
b y
 
M i s t r a l
 
b u t
 
n o t
 
b y
 
D e e p S e e k
 
—
 
u n l i k e
 
t h e
 
t w o
 
K n e e d l e - i n t e r n a l

c o m p a r i s o n s
 
a b o v e ,
 
w h i c h
 
a r e
 
u n a m b i g u o u s
 
u n d e r
 
b o t h
 
j u d g e s .

## Step 7 — Reference check vs the original 12-anchor chat evaluation

**Not a thesis result.** The 12-anchor chat evaluation is fully superseded by the 588-anchor run above; this is a directional sanity check only. Using just the 12 original anchors' API verdicts, recompute Precision@5 per config and compare the *ranking direction* to thesis Table 5.5 (Kneedle S=1.0 best, pct_dropoff 0.03 worst).

**Direction holds.** On the 12 originals the worst is pct_dropoff 0.03 (0.383) and the Kneedle configs top the list, matching Table 5.5. The one wobble is internal to Kneedle — at n=12, S=0.5 (0.700) edges S=1.0 (0.683) — which is exactly the noise Step 6 resolves at full scale. Nothing here feeds the headline numbers.

In [10]:
orig = json.load(open(ROOT / "outputs" / "full_scale" / "evaluation" / "anchors.json"))["anchors"]
orig_ids = {str(a["product_id"]) for a in orig}
orig_anchors = [a for a in ANCHORS if a in orig_ids]
assert len(orig_anchors) == 12, f"expected 12 original anchors present, got {len(orig_anchors)}"

rows = []
for c in CONFIGS:
    d = float(np.mean([yr[c]["deepseek_v4pro"][a] for a in orig_anchors]))
    mi = float(np.mean([yr[c]["mistral_large3"][a] for a in orig_anchors]))
    rows.append({"config": c, "deepseek_v4pro": round(d, 4),
                 "mistral_large3": round(mi, 4), "avg": round((d + mi) / 2, 4)})
ref12 = pd.DataFrame(rows).set_index("config").reindex(CONFIGS)
print("REFERENCE ONLY (12 original anchors) — not a thesis result:\n")
print(ref12.to_string())
worst = ref12["avg"].idxmin()
best = ref12["avg"].idxmax()
print(f"\nworst (avg): {worst} = {ref12['avg'].min():.4f}")
print(f"best  (avg): {best} = {ref12['avg'].max():.4f}")
print(f"Table 5.5 direction held: worst is pct_dropoff_0.03 -> {worst == 'pct_dropoff_0.03'}; "
      f"a Kneedle config tops the list -> {best.startswith('kneedle')}")
ref12

REFERENCE ONLY (12 original anchors) — not a thesis result:

                  deepseek_v4pro  mistral_large3     avg
config
pct_dropoff_0.03          0.3500          0.4167  0.3833
pct_dropoff_0.05          0.5333          0.5667  0.5500
pct_dropoff_0.10          0.5833          0.5833  0.5833
kneedle_0.3               0.6000          0.6000  0.6000
kneedle_0.5               0.7333          0.6667  0.7000
kneedle_1.0               0.6833          0.6833  0.6833

worst (avg): pct_dropoff_0.03 = 0.3833
best  (avg): kneedle_0.5 = 0.7000
Table 5.5 direction held: worst is pct_dropoff_0.03 -> True; a Kneedle config tops the list -> True

                  deepseek_v4pro  mistral_large3     avg
config
pct_dropoff_0.03          0.3500          0.4167  0.3833
pct_dropoff_0.05          0.5333          0.5667  0.5500
pct_dropoff_0.10          0.5833          0.5833  0.5833
kneedle_0.3               0.6000          0.6000  0.6000
kneedle_0.5               0.7333          0.6667  0.7000
kneedle_1.0               0.6833          0.6833  0.6833

## Step 8 — Summary

A final markdown roll-up is generated from the computed numbers and written to `analysis/analysis_report.md`, so it can be read on its own. The cell below builds it and prints it.

In [ ]:
best_cfg = precision_by_config.loc[precision_by_config["precision_at_5"].idxmax()]
worst_cfg = precision_by_config.loc[precision_by_config["precision_at_5"].idxmin()]

report = f"""# API evaluation — analysis summary

Two LLM judges (DeepSeek V4 Pro on DeepInfra fp8; Mistral Large 3 2512,
first-party) each rated all **13,845** anchor-candidate pairs over **588 anchors**
and six threshold configurations. **27,690** verdicts, every one valid, reasoning
disabled (0 reasoning tokens). Numbers below are anchor-averaged Precision@5
(thesis Eq. 4.1); pooled and anchor-averaged coincide (5 candidates/anchor, no gaps).

## 1. Headline precision (replaces Table 5.5)

| config | DeepSeek | Mistral |
|---|---|---|
""" + "".join(
    f"| {c} | {table55.loc[c, 'deepseek_v4pro']:.4f} | {table55.loc[c, 'mistral_large3']:.4f} |\n"
    for c in CONFIGS) + f"""
Best: **{best_cfg['config']}** ({best_cfg['model']} {best_cfg['precision_at_5']:.4f}).
Worst: **{worst_cfg['config']}** ({worst_cfg['model']} {worst_cfg['precision_at_5']:.4f}).
The ranking is monotone in threshold looseness and identical across both judges:
Kneedle S=1.0 > S=0.5 > S=0.3 > pct_dropoff 0.10 > 0.05 > 0.03.

## 2. Density stratum
Mean precision (all configs & models): sparse **{strat_summary['sparse']:.4f}**,
medium **{strat_summary['medium']:.4f}**, popular **{strat_summary['popular']:.4f}**
(popular/sparse = {strat_summary['popular']/strat_summary['sparse']:.2f}x). The
Section 5.3 density gap shows up in judged precision too — smaller than the ~2x
hop-survival gap but pointing the same way, inside every config.

## 3. Inter-model agreement
Agreement **{agree/n*100:.2f}%**, Cohen's kappa **{kappa:.4f}** (strong).
Disagreements ({n-agree:,}) lean one way: DeepSeek YES / Mistral NO **{b:,}** vs
the reverse **{c_:,}**. DeepSeek is the more lenient judge (YES rate
{p_deep_yes:.4f} vs {p_mist_yes:.4f}).

## 4. Reason codes
Same decisions, different labels: Mistral favours `same_need`
({dist['mistral_large3'].get('same_need', 0):,} vs {dist['deepseek_v4pro'].get('same_need', 0):,}),
DeepSeek favours `variant`
({dist['deepseek_v4pro'].get('variant', 0):,} vs {dist['mistral_large3'].get('variant', 0):,}).
88% of disagreements are `different_need <-> same_need`/`variant` label splits, not
deep semantic conflict.

## 5. Per-anchor spread
Mean acceptance ranges 0.000-1.000 across 588 anchors: **{(accs == 0).sum()}** never
accepted, **{(accs == 1).sum()}** always accepted. Basket count correlates weakly and
positively with acceptance (Spearman rho = {rho:.3f}, p = {pval:.2g}).

## 6. Bootstrap (10,000 resamples of 588 anchors)
Kneedle S=1.0 beats both S=0.3 and S=0.5: every 95% CI on the difference is above
zero and S=1.0 wins 100% of resamples for both judges. This **resolves** the
S=0.5-vs-S=1.0 tie the 12-anchor evaluation could not separate.

Boundary pair (Kneedle S=0.3, the worst Kneedle config, vs pct_dropoff 0.10, the
best drop-off config) is a different story: DeepSeek obs=+0.0150, 95% CI
[-0.0068, +0.0367] (crosses zero); Mistral obs=+0.0330, 95% CI [+0.0109, +0.0551]
(does not cross zero). At this one closest cross-method pair, Kneedle's edge over
drop-off is established by Mistral but not by DeepSeek.

## 7. Reference check (12 original anchors, NOT a thesis result)
On the 12 originals the Table 5.5 direction holds (pct_dropoff 0.03 worst; a
Kneedle config best). At n=12 S=0.5 edges S=1.0 — the exact noise Step 6 resolves.

## Surprising / worth flagging
- The two judges agree on the *decision* far more than on the *reason code*: kappa
  on YES/NO is 0.842, but they route ~6,000 pairs through different accepting
  buckets. Any reason-code-level analysis in the thesis must treat the codes as
  judge-specific, not interchangeable.
- DeepSeek ran on DeepInfra **fp8** (no full-precision endpoint exists on
  OpenRouter); Mistral was first-party unquantized. The judges are therefore not
  precision-matched — worth a sentence in the write-up.
- The density effect is real but weak at the anchor level (rho 0.23): threshold
  choice moves precision more than anchor popularity does.
"""
(ANALYSIS_DIR / "analysis_report.md").write_text(report)
print(report)

# API evaluation — analysis summary

Two LLM judges (DeepSeek V4 Pro on DeepInfra fp8; Mistral Large 3 2512,
first-party) each rated all **13,845** anchor-candidate pairs over **588 anchors**
and six threshold configurations. **27,690** verdicts, every one valid, reasoning
disabled (0 reasoning tokens). Numbers below are anchor-averaged Precision@5
(thesis Eq. 4.1); pooled and anchor-averaged coincide (5 candidates/anchor, no gaps).

## 1. Headline precision (replaces Table 5.5)

| config | DeepSeek | Mistral |
|---|---|---|
| pct_dropoff_0.03 | 0.4201 | 0.4075 |
| pct_dropoff_0.05 | 0.5469 | 0.5272 |
| pct_dropoff_0.10 | 0.6129 | 0.5874 |
| kneedle_0.3 | 0.6279 | 0.6204 |
| kneedle_0.5 | 0.6388 | 0.6248 |
| kneedle_1.0 | 0.6830 | 0.6724 |

Best: **kneedle_1.0** (deepseek_v4pro 0.6830).
Worst: **pct_dropoff_0.03** (mistral_large3 0.4075).
The ranking is monotone in threshold looseness and identical across both judges:
Kneedle S=1.0 > S=0.5 > S=0.3 > pct_dropoff 0.10 > 0.05 > 0.03.

## 2. Density stratum
Mean precision (all configs & models): sparse **0.5048**,
medium **0.5647**, popular **0.6790**
(popular/sparse = 1.35x). The
Section 5.3 density gap shows up in judged precision too — smaller than the ~2x
hop-survival gap but pointing the same way, inside every config.

## 3. Inter-model agreement
Agreement **92.11%**, Cohen's kappa **0.8421** (strong).
Disagreements (1,093) lean one way: DeepSeek YES / Mistral NO **643** vs
the reverse **450**. DeepSeek is the more lenient judge (YES rate
0.5175 vs 0.5036).

## 4. Reason codes
Same decisions, different labels: Mistral favours `same_need`
(4,227 vs 1,129),
DeepSeek favours `variant`
(5,698 vs 2,486).
88% of disagreements are `different_need <-> same_need`/`variant` label splits, not
deep semantic conflict.

## 5. Per-anchor spread
Mean acceptance ranges 0.000-1.000 across 588 anchors: **24** never
accepted, **48** always accepted. Basket count correlates weakly and
positively with acceptance (Spearman rho = 0.230, p = 1.7e-08).

## 6. Bootstrap (10,000 resamples of 588 anchors)
Kneedle S=1.0 beats both S=0.3 and S=0.5: every 95% CI on the difference is above
zero and S=1.0 wins 100% of resamples for both judges. This **resolves** the
S=0.5-vs-S=1.0 tie the 12-anchor evaluation could not separate.

Boundary pair (Kneedle S=0.3, the worst Kneedle config, vs pct_dropoff 0.10, the
best drop-off config) is a different story: DeepSeek obs=+0.0150, 95% CI
[-0.0068, +0.0367] (crosses zero); Mistral obs=+0.0330, 95% CI [+0.0109, +0.0551]
(does not cross zero). At this one closest cross-method pair, Kneedle's edge over
drop-off is established by Mistral but not by DeepSeek.

## 7. Reference check (12 original anchors, NOT a thesis result)
On the 12 originals the Table 5.5 direction holds (pct_dropoff 0.03 worst; a
Kneedle config best). At n=12 S=0.5 edges S=1.0 — the exact noise Step 6 resolves.

## Surprising / worth flagging
- The two judges agree on the *decision* far more than on the *reason code*: kappa
  on YES/NO is 0.842, but they route ~6,000 pairs through different accepting
  buckets. Any reason-code-level analysis in the thesis must treat the codes as
  judge-specific, not interchangeable.
- DeepSeek ran on DeepInfra **fp8** (no full-precision endpoint exists on
  OpenRouter); Mistral was first-party unquantized. The judges are therefore not
  precision-matched — worth a sentence in the write-up.
- The density effect is real but weak at the anchor level (rho 0.23): threshold
  choice moves precision more than anchor popularity does.

### Output files

All under `analysis/`:

- `precision_by_config.csv` — Step 1 headline table
- `precision_by_config_stratum.csv` — Step 2 density split
- `agreement.md` — Step 3 agreement + kappa + disagreement direction
- `reason_code_crosstab.csv` — Step 4 disagreement reason cross-tab
- `anchor_level.csv` — Step 5 per-anchor breakdown
- `bootstrap_ci.json` — Step 6 bootstrap CIs
- `analysis_report.md` — Step 8 full summary